#! /bin/bash

# startup programs
xwallpaper --center ~/Pictures/omni-man-invincible-series-art-hd-wallpaper-uhdpaper.com-132@1@n.jpg &
pgrep -x sxhkd > /dev/null || sxhkd &
b.sh | lemonbar -p -B#1F1D19 -F#DEDEDE -u 3  -f "monospace-10" -g x27 | $SHELL &
# numlockx on &
picom &
pidof bspswallow || bspswallow &

# mounting drives
sudo mount /dev/disk/by-label/Games Games &
sudo mount /dev/disk/by-label/VMs /mnt/C &
sudo mount /dev/disk/by-label/Data\\x20waala /mnt/D &

#var=$(xinput | grep Tou | awk '{print $6}') && var=${var##id=} && xinput --disable $var &

# bspwm configs
bspc monitor -d I II III 
bspc config border_width         4
bspc config split_ratio          0.5
bspc config gapless_monocle      true
bspc config bottom_monocle_padding -9
bspc config left_monocle_padding -9
bspc config right_monocle_padding -9
bspc config window_gap           7 
bspc config normal_border_color  \#161b1d
bspc config focused_border_color \#25770e 
bspc config automatic_scheme     longest_side
bspc desktop III -l monocle
bspc config top_padding 30
bspc config right_padding 9
bspc config left_padding 9
bspc config bottom_padding 9 
bspc config pointer_action1 move

# rules for application
bspc rule -a discord desktop='^3'  
bspc rule -a KiCad desktop='^3'  
bspc rule -a qutebrowser desktop='^3'  
bspc rule -a surf desktop='^3' state=tiled
bspc rule -a krita desktop='^3'  
bspc rule -a Chromium-browser desktop='^3'
bspc rule -a chromium desktop='^3'
bspc rule -a Thunar state=floating 
bspc rule -a Pavucontrol state=floating
bspc rule -a Steam desktop='^2' state=floating
bspc rule -a Lutris desktop='^2'
bspc rule -a steam desktop='^2' state=floating
bspc rule -a vlc state=floating
bspc rule -a antimicrox state=floating 
bspc rule -a Gimp desktop='^3'
bspc rule -a gnome-calculator state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Calculator state=floating
bspc rule -a calculator state=floating
