#! /bin/bash

d

bspc monitor -d I II III 
bspc config border_width         3
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_monocle_padding 3
bspc config window_gap           7 
bspc config normal_border_color  \#383236
bspc config focused_border_color \#25770e 
bspc config automatic_scheme     longest_side
bspc desktop III -l monocle

# rules and stuff
bspc rule -a discord desktop='^3'  
bspc rule -a atom state="tiled" 
bspc rule -a steam state=pseudo_tiled desktop="^2" 
