#! /bin/bash

d

bspc monitor -d I II III 
bspc config border_width         3
bspc config split_ratio          0.5
bspc config gapless_monocle      true
bspc config bottom_monocle_padding -9
bspc config left_monocle_padding -9
bspc config right_monocle_padding -9
bspc config window_gap           7 
bspc config normal_border_color  \#161b1d
bspc config focused_border_color \#25770e 
bspc config automatic_scheme     longest_side
bspc desktop III -l monocle
bspc config top_padding 30
bspc config right_padding 9
bspc config left_padding 9
bspc config bottom_padding 9 

# rules and stuff
bspc rule -a discord desktop='^3'  
bspc rule -a atom state="tiled"
bspc rule -a thunar state="floating" 
