#!/bin/bash

bat=$(cat /sys/class/power_supply/BAT1/capacity)

( [ -z $(pgrep pcmode) ] && [ $(cat /sys/class/power_supply/BAT1/status) == "Discharging" ] && [ $bat -lt 30 ] ) && notify-send -u critical "Battery is low: $(cat /sys/class/power_supply/BAT1/capacity)%"

[ $(cat /sys/class/power_supply/BAT1/status) == "Discharging" ] && [ $bat -lt 20 ] && notify-send -u critical "Laptop will shutdown in 1 min" && sleep 60 && sudo shutdown now
