#!/bin/bash

( [ -z $(pgrep pcmode) ] && [ $(cat /sys/class/power_supply/BAT1/status) == "Discharging" ] && [ $(cat /sys/class/power_supply/BAT1/capacity) -lt 30 ] ) && notify-send -u critical "Battery is low: $(cat /sys/class/power_supply/BAT1/capacity)%"
