#!/bin/bash

[ -z $1 ] && mode=$(printf "noloop\nall\ncomp\nclose" | dmenu -sb "dark green") || mode=$1
[ -z $mode ] && exit 1

# runs a script for removing accel there's isnt any but still
mouse

loop=true

[ $mode == "noloop" ] && loop=false && mode="all"
[ $mode == "all" ] && sudo umount /mnt/C /mnt/D; killall -q lemonbar && killall -q b.sh && bspc config top_padding 7 && mode="comp"
[ $mode == "comp" ] && killall -q picom
[ $mode == "close" ] && xrandr --output eDP-1 --scale 1x1 && bspc quit && killall -q pcmode 

while $loop; do
sleep 20;
temp=$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000));
mem=$(($(free | awk '/^Mem:/{print $3}')/1024));
batt=$(cat /sys/class/power_supply/BAT1/status)
charg=$(cat /sys/class/power_supply/BAT1/capacity)

[ ${batt:0:1} == "D" ] && notify-send -u critical "Warning laptop not charging $(cat /sys/class/power_supply/BAT1/capacity)% $(date "+%H:%M")";
[ $mem -gt 13950 ] && notify-send "memory usage is high: $(free -h | awk '/^Mem:/{print $3"/"$2}') $(date "+%H:%M")";
[ $temp -gt 82 ] && notify-send "temp is high: $temp°C $(date "+%H:%M")";

done
