#!/bin/bash

mode=$(printf "resall\nall\ncomp\nclose" | dmenu -sb "dark green")
time=0

[ -z $mode ] && exit 1
#[ $mode == "resall" ] && xrandr --output eDP-1 --scale 0.5333x0.5333 && mode="all" # this is for 1024 x 576
[ $mode == "resall" ] && xrandr --output eDP-1 --scale 0.6667x0.6667 && mode="all" # this one was for uh...1280 x 720
[ $mode == "all" ] && killall -q lemonbar && killall -q b.sh && bspc config top_padding 7 && mode="comp"
[ $mode == "comp" ] && killall -q picom
[ $mode == "close" ] && xrandr --output eDP-1 --scale 1x1 && bspc quit && killall -q pcmode 

# doesnt work properly as only one statement can be true
#case $mode in
#    "resall") xrandr --output eDP-1 --scale 0.6667 && mode=all ;;
#    "all") killall -q lemonbar && killall -q b.sh && bspc config top_padding 7 && mode=comp ;;
#    "comp") killall -q picom ;;
#    "exit") xrandr --output eDP-1 --scale 1 && bspc quit && killall -q pcmode && killall -q steam ;;
#esac

while true; do

temp=$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000));
mem=$(($(free | awk '/^Mem:/{print $3}')/1024));
batt=$(cat /sys/class/power_supply/BAT1/status)
charg=$(cat /sys/class/power_supply/BAT1/capacity)
sleep 10;

[ ${batt:0:1} == "D" ] && notify-send -u critical "Warning laptop not charging $(cat /sys/class/power_supply/BAT1/capacity)% $(date "+%H:%M")";
[ $mem -gt 5950 ] && notify-send "memory usage is high: $(free -h | awk '/^Mem:/{print $3"/"$2}') $(date "+%H:%M")";
[ $temp -gt 78 ] && notify-send "temp is high: $temp°C $(date "+%H:%M")";
[ $(($time%120)) == 0 ] && notify-send "Current Session: $((time/60)) mins";

time=$(($time + 10))
done
