#!/bin/bash

mode=$(printf "resall\nall\ncomp\nexit" | dmenu -sb "dark green")

[ -z $mode ] && exit 1
[ $mode == "resall" ] && xrandr --output eDP-1 --scale 0.6667x0.6667 && mode="all"
[ $mode == "all" ] && killall -q lemonbar && killall -q b.sh && bspc config top_padding 7 && mode="comp"
[ $mode == "comp" ] && killall -q picom
[ $mode == "exit" ] && xrandr --output eDP-1 --scale 1x1 && killall -q pcmode && lemonstart && b.sh | lemonbar -p -B#1F1D19 -F#DEDEDE -u 3  -f "monospace-10" -g x27 | $SHELL

# doesnt work properly as only one statement can be true
#case $mode in
#    "resall") xrandr --output eDP-1 --scale 0.6667 && mode=all ;;
#    "all") killall -q lemonbar && killall -q b.sh && bspc config top_padding 7 && mode=comp ;;
#    "comp") killall -q picom ;;
#    "exit") xrandr --output eDP-1 --scale 1 && bspc quit && killall -q pcmode && killall -q steam ;;
#esac

while true; do

temp=$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000));
mem=$(($(free | awk '/^Mem:/{print $3}')/1024));
batt=$(cat /sys/class/power_supply/BAT1/status)
charg=$(cat /sys/class/power_supply/BAT1/capacity)

[ ${batt:0:1} == "D" ] && notify-send -u critical "Warning laptop not charging $(cat /sys/class/power_supply/BAT1/capacity)% $(date "+%H:%M")";
[ $mem -gt 5000 ] && notify-send "memory usage is high: $(free -h | awk '/^Mem:/{print $3"/"$2}') $(date "+%H:%M")";

[ $temp -gt 79 ] && notify-send "temp is high: $temp°C $(date "+%H:%M")";
sleep 10;

done
