#!/bin/bash

notify-send "Updating dotfiles-n-scripts"

dir=/home/noyb/.local/share/dotfiles-n-scripts/

str=""

for i in $(ls -ap $dir | grep -v "\.\(\w\+\)\?/")
    do  targ=$(find ~ -maxdepth 2 -name "${i%/}")

    ( [ ! -z $targ ] && [ $i == ${i%/} ] && [ $(( $(stat -c "%Y" $targ) - $(stat -c "%Y" $dir$i) )) -gt 0 ] ) && cp $targ $dir && str="${str} $i"

    ( [ ! -z $targ ] && [ $i != ${i%/} ] && [ $(( $(stat -c "%Y" $targ) - $(stat -c "%Y" $dir${i%/}) )) -gt 0 ] ) && cp -r --remove-destination $targ $dir && str="${str} $i"
done

git -C $dir add -q .

[ -n "$str" ] && git -C $dir commit -q -a -m "updated $str" && git -C $dir push -q origin main && notify-send "The following have been updated $str"

[ -z "$str" ] && notify-send "There is nothing to update"
