#!/bin/bash

notify-send "Updating dotfiles-n-scripts"

dir=/home/noyb/.local/share/dotfiles-n-scripts/
str=""

for i in $(ls -ap $dir | grep -v /); 
    do targ=$(find ~ -maxdepth 2 -name "$i")
    ( [ ! -z $targ ] && [ $(( $(stat -c "%Y" $targ) - $(stat -c "%Y" $dir$i) )) -gt 0 ] ) && cp $targ $dir && str="${str} $i"
done

for i in $(ls -ap $dir | grep  /); 
    do targ=$(find ~ -maxdepth 2 -name "${i%/}")
    ( [ ! -z $targ ] && [ $(( $(stat -c "%Y" $targ) - $(stat -c "%Y" $dir${i%/}) )) -gt 0 ] ) && cp -r --remove-destination $targ $dir && str="${str} ${i%/}"
done

[ -n "$str" ] && git -C $dir commit -q -a -m "updated $str" && git -C $dir push -q origin main && notify-send "The following have been updated $str"
[ -z "$str" ] && notify-send "There is nothing to update"
